name: API tests run
on:
 workflow_dispatch:
 
jobs:
  deploy-and-test-run:
    name: RestSharp run
    runs-on: ubuntu-latest
    steps:
      - name: Pull API Docker image
        run: docker pull coherentsolutions/rest-training:1.0
      
      - name: Run API Docker container
        run: docker run -d -p 3355:8082 coherentsolutions/rest-training:1.0      
      
      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Get Repository code
        uses: actions/checkout@v4
        
      - name: Restore NuGet packages
        run: dotnet restore Rest.sln
      
      - name: Run API tests
        run: dotnet test Rest.sln --logger "trx"

      - name: Verify allure-results directory
        if: always()
        continue-on-error: true
        run: |
         if [ -d "Rest/bin/Debug/net8.0/allure-results" ]; then
         echo "âœ… allure-results directory exists."
         ls -la Rest/bin/Debug/net8.0/allure-results
         else
         echo "âŒ allure-results directory does NOT exist."
         exit 1

      - name: Search for allure-results folder
        if: always()
        continue-on-error: true
        run: |
         echo "ðŸ” Searching for allure-results folder..."
         FOUND_PATH=$(find . -type d -name "allure-results" | head -n 1)
         if [ -n "$FOUND_PATH" ]; then
         echo "âœ… Found allure-results at: $FOUND_PATH"
         ls -la "$FOUND_PATH"
         else
         echo "âŒ allure-results folder not found."
         exit 1
         fi
        
      - name: Load Allure Test Report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Build Allure test report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_report: allure-report
          allure_results: Rest/bin/Debug/net8.0/allure-results
          
      - name: Upload allure report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
          retention-days: 15
          
      - name: Deploy allure report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

      - name: Provide link to the Allure report
        if: always()
        run: echo "## ðŸ“Š [Allure report available here](https://${{ github.repository_owner }}.github.io/Rest/${{ github.run_number }})" >> $GITHUB_STEP_SUMMARY 
